[project]
name = "lidar_lib"
description = "A library to connect to the Seyond LiDAR"
dynamic = ["version"]
#version = "1.0"
authors = [ {name = "Paul M. B. Bendixen", email = "pbe@trifork.com"} ]
maintainers = [ {name = "Paul M. B. Bendixen", email = "pbe@trifork.com"} ]

[build-system]
requires = [
	"conan >= 2",
	"scikit-build-core"
]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
wheel.py-api = "cp38"
build.targets = ["inno"]
cmake.args = ["--preset release"]

[tool.scikit-build.metadata.version]
provider = "scikit_build_core.metadata.regex"
input = "CMakeLists.txt"
regex = 'project\s*\([^\)]*VERSION\s+(?P<value>[0-9\.]+)'



